# Forces new Travis-CI Infrastructure
sudo: false

language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

services:
  - memcached
  - redis-server

before_script:
  - composer install
  - if [ $TRAVIS_PHP_VERSION == "5.6" ]; then phpenv config-add build/config/travis/phpenv/memcached.ini; fi
  - if [ $TRAVIS_PHP_VERSION == "5.6" ]; then phpenv config-add build/config/travis/phpenv/redis.ini; fi

script:
  - libraries/vendor/bin/robo test
  - libraries/vendor/bin/robo check:style
